plugins {
	id 'java-library'
	id 'eclipse'
}


base.archivesName = "processor"

sourceSets.main.java.srcDirs = ["src"]

java {
	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    addAll(rootProject.repositories)
}

dependencies {
	implementation 'com.squareup:javapoet:1.13.0'
	implementation "com.google.auto:auto-common:1.2.2"
	compileOnly 'com.google.auto.service:auto-service-annotations:1.1.1'
	annotationProcessor 'com.google.auto.service:auto-service:1.1.1'
    compileOnly "Anuken:Mindustry:${rootProject.mindustryVersion}"
    
    compileOnly 'net.ltgt.gradle.incap:incap:0.3'
    annotationProcessor 'net.ltgt.gradle.incap:incap-processor:0.3'
}

tasks.named('build') {
    finalizedBy(rootProject.tasks.named('aptGenerateSources'))
}
